# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200
mixer_update_interval: False

# use the Q_Learner to train
agent_output_type: "q"
learner: "sq_learner"
mixer: "sq_mixer"
mixing_embed_dim: 64
double_q: True
arch: "observation_action"
n_step: 1
sample_size: 5
w_shared_params: True
mixer_lr: 0.005
w_constraint_coef: 0.001

network_size: "small"

name: "sq"